### ISSUE TITLE
403 Cuando sube archivo a canal

### ISSUE THREAD

**Issue by jjsanchez88** [ivangomez/M365SatMadV_SpfxAddin#1]
Hola Iván,

mi nombre es Juanjo y he asistido esta mañana a tu charla del Microsoft 365 Virtual Summit. Ha estado genial y me ha parecido súper interesante. 

He clonado el repo y todo funciona perfectamente, salvo el paso de subir (hacer el put) el archivo adjunto al canal seleccionado. 

Me devuelve siempre un 403

![Untitled](https://user-images.githubusercontent.com/55842834/80732149-2f70a000-8b0c-11ea-97d2-13a61b07789b.png)

**Comment by ivangomez** [comment]
Hola Juanjo,
Me alegro mucho de que mi charla te pareciera interesante, ya con eso que me dices ha merecido la pena el esfuerzo de prepararla.
A raíz de tu comentario volví a ejecutar unas cuantas pruebas para ver si había algún tema de permisos que se me hubiera escapado, estuve probando con usuarios que eran administradores del Team y con usuarios que no lo eran, pero todos funcionaban correctamente. Con lo único que no he probado son con usuarios externos. En teoría si perteneces al Team tienes permisos para subir archivos con lo que no debería haber problema.
Si me das más datos de cómo lo probaste, puedo investigar a ver por qué puede ser.

**Comment by jjsanchez88** [comment]
Creo que el problema es que lo intente con el administrador del tenant...con otros usuarios del tenant me ha fucionado perfectamente :-)

**Comment by ivangomez** [comment]
Fenomenal! Si hay cualquier otro problema me dices...
